theme: jekyll-theme-minimal
title: poetry
description: 當繆思來臨時
navigation:
  - title: biography
    url: https://zenkarsha.github.io/biography/
  - title: muse
    url: https://zenkarsha.github.io/muse/
  - title: whisper
    url: https://zenkarsha.github.io/whisper/
  - title: favorite
    url: https://zenkarsha.github.io/favorite/
  - title: works
    url: https://zenkarsha.github.io/works/
  - title: blog
    url: https://zenkarsha.github.io/blog/

